config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :gardens do
    resources :reviews, only: [:create]
    resources :bookings, only: [:new, :create]
  end
  resources :users, only: [:show, :edit, :update, :destroy] do
    resources :bookings, only: [:show, :edit, :update]
  end
  resources :bookings, only: [:destroy, :index, :show]
  resources :reviews, only: [:edit, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :garden
  belongs_to :user

  validates :start_date, presence: true
  validates :end_date, presence: true

  def start_time
    start_date
  end

  def end_time
    end_date
  end
end

app/models/garden.rb
class Garden < ApplicationRecord

  include PgSearch::Model
  pg_search_scope :search_by_location,
      against: [:location],
      using: {
        tsearch: { prefix: true }
      }

  PURPOSE = ["Garden party", "Growing vegetables", "Growing flowers", "Growing herbs"]

  validates :name, presence: true, uniqueness: true
  validates :location, presence: true
  validates :price_per_day, presence: true
  validates :purpose, inclusion: { in: PURPOSE }

  has_many :reviews, dependent: :destroy
  has_many :bookings, dependent: :destroy
  belongs_to :user

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  mount_uploader :photo, PhotoUploader
end

app/models/review.rb
class Review < ApplicationRecord
  RATING = [0, 1, 2, 3, 4, 5]
  belongs_to :user
  belongs_to :garden

  validates :description, presence: true, length: { minimum: 20 }
  validates :rating, presence: true
  validates :rating, inclusion: { in: RATING }


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews
  has_many :gardens
  has_many :bookings, dependent: :destroy
  validates :username, presence: true
  validates :username, uniqueness: true

  mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :bio, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  before_action :set_garden, only: [:new, :create]
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  def index
    @bookings = policy_scope(current_user.bookings)
  end

  def new
    @booking = Booking.new
    @garden = Garden.find(params[:garden_id])
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.garden = @garden
    @booking.user = current_user
    authorize @booking

    if @booking.save
      redirect_to bookings_path
    else
      render :new
    end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking.update(booking_params)
    redirect_to bookings_path
    authorize @booking
  end

  def destroy
    @booking.destroy
    authorize @booking
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:garden_id, :start_date, :end_date)
  end

  def set_garden
    @garden = Garden.find(params[:garden_id])
  end

  def set_booking
    @booking = Booking.find(params[:id])
    authorize @booking
  end
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  before_action :set_garden, only: [:show, :edit, :update, :destroy]

  def index
    @gardens = policy_scope(Garden).order(created_at: :desc)

    @geogardens = Garden.geocoded #returns flats with coordinates

    @markers = @geogardens.map do |garden|
      {
        lat: garden.latitude,
        lng: garden.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { garden: garden }),
        image_url: helpers.asset_url('Group.png'),
        id: garden.id
      }
    end

  end

  def new
    @garden = Garden.new
    authorize @garden
  end

  def show
    @review = Review.new
    @booking = Booking.new

    @markers = [
      {
        lat: @garden.latitude,
        lng: @garden.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { garden: @garden })
      }
    ]
  end

  def create
    @garden = Garden.new(garden_params)
    @garden.user = current_user
    authorize @garden
    if @garden.save
      redirect_to garden_path(@garden)
    else
      render :new
    end
  end

  def update
    @garden.update(garden_params)
    authorize @garden
    redirect_to garden_path(@garden)
  end

  def edit
    authorize @garden
  end

  def destroy
    authorize @garden
    @garden.destroy
  end

  private

  def set_garden
    @garden = Garden.find(params[:id])
    authorize @garden
  end

  def garden_params
    params.require(:garden).permit(:name, :location, :price_per_day, :description, :purpose, :size, :photo, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:destroy]

  def create
    @review = Review.new(review_params)
    @garden = Garden.find(params[:garden_id].to_i)
    @review.rating = params[:review][:rating].to_i
    @review.garden = @garden
    @review.user = current_user
    if @review.save
      respond_to do |format|
        format.html { redirect_to garden_path(@garden) }
        format.js  # <-- will render `app/views/reviews/create.js.erb`
      end
    else
      respond_to do |format|
        format.html { render 'gardens/show' }
        format.js  # <-- idem
      end
    end
    authorize @review
  end

  def destroy
    @garden = Garden.find(@review.garden_id)
    @review.destroy
    # redirect_to garden_path(@garden)
    authorize @review
  end

  private

  def set_review
    @review = Review.find(params[:id])
    authorize @review
  end

  def review_params
    params.require(:review).permit(:description, :rating, :user_id, :garden_id)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @user = current_user
  end

  def edit
  end

  def update
    current_user.update(user_params)
    redirect_to user_path(@user)
  end

  private

  def user_params
    params.require(:users).permit(:email, :username, :bio)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    current_user
    authorize current_user
    # @garden.user = @garden
  end

  def edit
    @user = current_user
    authorize @user
  end

  def update
    current_user.update(user_params)
    @user = current_user
    authorize @user
    redirect_to user_path(current_user)
  end

  private

  def user_params
    params.require(:user).permit(:email, :username, :bio, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/bookings/index.html.erb
<div class="bookings-container">
  <% @bookings.each do |booking| %>
    <div class="bookings-card" data-toggle="modal" data-target="#exampleModalCenter<%= booking.id %>">
      <% if booking.garden.photo.model[:photo] %>
        <%= cl_image_tag(booking.garden.photo, crop: :fill) %>
      <% else %>
        <%= cl_image_tag("dyapkyhkbvoxmv3nxmbu", crop: :fill) %>
      <% end  %>
      <div class="bookings-text">
        <strong><em><%= booking.garden.name %></em></strong>
        <div class="bookings-timings">
        <p><strong>Start:</strong> <%= booking.start_date.strftime("%m/%d/%Y") %></p>
        <p><strong>End:</strong> <%= booking.end_date.strftime("%m/%d/%Y") %></p>
        </div>
      </div>
      <div class="bookings-delete">
      <% if policy(booking).destroy? %>
        <%= link_to booking_path(booking), method: :delete do %>
          <i class="fas fa-trash-alt" ></i>
        <% end %>
      <% end %>
      </div>
    </div>

    <div class="modal fade" id="exampleModalCenter<%= booking.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <strong><h2 class="modal-title" id="exampleModalLongTitle"><%= booking.garden.name %></h2></strong>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <h2>Description: <%= booking.garden.description %></h2>
            <h3><strong>Start:</strong> <%= booking.start_date.strftime("%m/%d/%Y") %> </h3>
            <h3><strong>End:</strong> <%= booking.end_date.strftime("%m/%d/%Y") %> </h3>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>



<div id="calendar">
 <%= month_calendar events: @bookings do |date, bookings| %>
   <%= date %>
   <% bookings.each do |booking| %>
     <div class="card-background-color-white">
       <%= booking.garden.name %>
     </div>
   <% end %>
 <% end %>
</div>

app/views/bookings/new.html.erb
<%= simple_form_for [@garden, @booking] do |f| %>
  <%= f.input :start_date, as: :date %>
  <%= f.input :end_date, as: :date %>
  <%= f.button :submit %>
<% end %>

app/views/gardens/_info_window.html.erb
<div class="container">
  <div class="row">
    <img src="<%= garden.photo %>" alt="">
  </div>
  <div class="row">
    <%= link_to garden_path(garden) do %>
    <h4 class="title"><%= garden.name %></h4>
    <p class="info"><%= garden.purpose %></p>
    <% end %>
  </div>
</div>

app/views/gardens/_reviews.html.erb
<div class="review-container" id="reviews">
  <h4>Reviews</h4>
  <h5 class="review-spacing"><%= pluralize garden.reviews.size, "review" %></h5>
  <% if garden.reviews.blank? %>
    <p class="review-spacing">Be the first to leave a review</p>
  <% else %>
    <% garden.reviews.each do |review| %>
      <%= render 'reviews/show', review: review %>
    <% end %>
  <% end %>
  <% if current_user != garden.user %>
    <div class="btn-review">
      <button type="button" class="btn btn-success" data-toggle="modal" data-target="#exampleModalLong">
        Leave a review
      </button>
    </div>
  <% end %>
</div>

app/views/gardens/index.html.erb
<div class="index-container">
  <div clas="row">
    <div class="align-items-left header">
    <p>Available Gardens</p>
    </div>
  </div>

  <div class="row">
    <div class="col-8">
      <div class="row">
      <% @gardens.each do |garden| %>
        <div class="col-4 garden-card hover" data-garden-id="<%= garden.id %>">
          <% if garden.user == current_user %>
          <p class="your_garden">Your garden</p>
          <% end %>
          <%= link_to garden_path(garden) do %>
          <%= cl_image_tag(garden.photo, height: 200,
             crop: :fill) %>
            <div class="card-info">
              <p class="purpose"><%= garden.purpose.upcase %></p>
              <h3 class="card-title"><%= garden.name %> </h3>
              <p class="card-text m-0 p-0">£<%= garden.price_per_day %>/day | <%= garden.size %>m²</p>
              <div>
                <% if garden.reviews.empty? %>
                  <% 5.times do %>
                  <i class="far fa-star yellow"></i>
                  <% end %>
                <% else %>
                  <% ratings = [] %>
                  <% garden.reviews.each do |review| %>
                  <% ratings << review.rating %>
                  <% end %>
                  <% rating = (ratings.sum) / ratings.length %>
                  <% rating.times do %>
                    <i class="fas fa-star yellow"></i>
                  <% end %>
                  <% empty = 5 - rating %>
                  <% empty.times do %>
                    <i class="far fa-star yellow"></i>
                  <% end %>
                <% end %>
              </div>
            </div>

        </div>
        <% end %>
      <% end %>
      </div>
    </div>
    <div class="col-4">
      <div
      id="map"
      style="width: 100%;
      height: 500px;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
      ></div>
    </div>
  </div>
</div>

app/views/gardens/new.html.erb
<div class="new-body" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
         url('<%= cl_image_path 'https://res.cloudinary.com/nmozzer/image/upload/v1566305175/benjamin-combs-wuU_SSxDeS0-unsplash_sdgwbl.jpg', cloud_name: 'nmozzer' %>')">
  <%= render 'shared/home_navbar' %>
  <div class="new-banner">
    <div class="new-card">
      <div>
        <h1>Hello Garden Owner!</h1>
      </div>
      <div>
        <p>See your garden used to its full potential, rent it out for a range of uses so that you can make money off of your outdoor space</p>
      </div>
      <div>
        <button type="button" class="btn btn-success w-100" data-toggle="modal" data-target=".bd-example-modal-lg">Get Started</button>
      </div>
    </div>
  </div>
</div>

<div class="container">

  <div class="">
    <h2 class="text-center text-lger">How it works</h2>
    <div class="info-cards">
      <div class="info-card">
        <i class="fas fa-tractor fill-green"></i>
        <h4>Allota farm</h4>
        <p>Rent a larger space for more serious growers.</p>
      </div>
      <div class="info-card">
        <i class="fas fa-spa fill-green"></i>
        <h4>Allota ment</h4>
        <p>Rent a smaller space for a green fingered enthusiast.</p>
      </div>
      <div class="info-card">
        <i class="fas fa-glass-cheers fill-green"></i>
        <h4>Allota fun</h4>
        <p>Rent your garden for a garden party.</p>
      </div>
    </div>
  </div>

   <div class="row">
     <%= image_tag('gardeningimage.jpg', class: "quoteimage") %>
          <div class="quote-text">
      <i class="fas fa-quote-left"></i>
      <h3>I love sharing my little garden with other veg-growers.</h3>
      <p >Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium porro autem harum vel ipsa optio cum velit, sapiente.</p>
     </div>
   </div>
</div>
<div class="bottom-new-container" style="background-image: url('<%= image_url 'nice-garden.jpg' %>')">
  <div>
    <h1>Ready to start?</h1>
  </div>
  <div>
    <button type="button" class="btn btn-light" data-toggle="modal" data-target=".bd-example-modal-lg">Get Started</button>
  </div>
</div>


<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <h2 class="text-center text-lger">Fill in the details of your Garden!</h2>
      <div class="form-padding">
        <%= simple_form_for @garden do |f| %>
        <div class="form-container d-flex" >
          <div class="form-main-body">
            <%= f.input :name %>
            <%= f.input :price_per_day %>
            <%= f.input :size %>
            <%= f.input :location %>
            <%= f.input :purpose, collection: Garden::PURPOSE %>
          </div>
          <div class="form-secondary-body">
            <%= f.input :description, input_html: {rows: 9} %>
            <%= f.input :photo %>
            <%= f.input :photo_cache, as: :hidden %>
          </div>

        </div>
        <div class="submit-center">
            <%= f.button :submit, "List your Garden!", class: "new-submit btn btn-success" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Let It Grow</title>
    <link rel="stylesheet" href="plantblack.png">
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.50.0/mapbox-gl.css' rel='stylesheet' />
    <link rel="shortcut icon" type="image/png" href="<%= asset_path('favicon.png') %>">
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <% if !current_page?(root_path) && !current_page?(new_garden_path) %>
        <%= render "shared/navbar" %>
    <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <% if !current_page?(root_path)%>
        <%= render "shared/footer" %>
    <% end %>
    <%= yield :before_js %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= yield :after_js %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="body" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
         url('<%= cl_image_path 'https://res.cloudinary.com/nmozzer/image/upload/v1566303724/slack-imgs.com_ckshqr.jpg', cloud_name: 'nmozzer' %>')">
  <%= render 'shared/home_navbar' %>
  <div class="card">
    <div class="tag">
      <h1>Rent an outside space.</h1>
    </div>
    <div class="search-bar">
      <div>Where</div>
      <div class="searching">
        <%= form_tag gardens_path, method: :get do %>
          <%= text_field_tag :search, nil, class: "input-field" %>
          <div class="flex-btns" id="green-button">
            <%= submit_tag 'Search', class: "btn btn-success" %>
            <%= link_to gardens_path do  %>
              <button type="button" class="btn btn-success">Take A Walk Through The Gardens</button>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/reviews/_show.html.erb
<div class="review-show" data-garden-id="<%= @garden.id %>">
  <div class="review-info-small space-between">
    <p id="review-name"><%= review.user.username %></p>
    <div>
       <p class="reviewrating"> Rating:</p>
       <% review.rating.times do %>
         <i class="fas fa-star yellow"></i>
       <% end %>
       <% empty = 5 - review.rating %>
       <% empty.times do %>
         <i class="far fa-star yellow"></i>
         <% end %>
    </div>
  </div>
  <div>
    <p><%= review.description %> </p>
  </div>
  <% if policy(review).destroy? %>
    <%= link_to review_path(review), method: :delete, remote: true do  %>
      <i class="fas fa-trash-alt" ></i>
    <% end %>
  <% end %>
</div>

app/views/reviews/create.js.erb
console.log('Hi');
reviews = document.getElementById('reviews');
reviews.innerHTML = "";
reviews.innerHTML = "<%= j render 'reviews', garden: @garden %>"

hideModal()

app/views/shared/_home_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-lewagon logo navbar-transparent">
  <div class="navbar-search d-flex align-items-center">
    <%= link_to root_path, class: "navbar-brand" do %>
      <div id="growlogo">
        <h1 class="logotext">let it gr<img class="plantlogo" src="<%= asset_path('plantwhite.png') %>" alt="">w</h1></i>
      </div>
      <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item light-hover">
          <%= link_to "List my garden", "#newgardenmodal", class: "nav-link", "data-toggle": "modal" %>
        </li>
        <li class="nav-item light-hover">
          <%= link_to "Find a garden", gardens_path, class: "nav-link" %>
        </li>
        <li class="nav-item light-hover">
          <%= link_to "My bookings", bookings_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.url.nil? %>
            <%= image_tag('avatar-default-picture.jpg', class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
          <% else  %>
            <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item d-flex light-hover">
          <%= render 'devise/sessions/new', class: "nav-link" %>
          <%= render 'devise/registrations/new', class: "nav-link" %>
          <%= link_to "Gardens", gardens_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<div id="newgardenmodal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <p>List your garden</p>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body row">
      <p class="modaltext col-10">Make the most of your outside space whilst helping others to live more sustainably. </p>
      <%= link_to new_garden_path do  %>
      <p class="modalplant col-2"><i class="fab fa-pagelines"></i></p>
      <% end %>
      </div>
      <div class="modal-footer">
        <%= link_to "Find out more", new_garden_path, id: "modallink" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm nav-border navbar-light navbar-lewagon logo">
  <div class="navbar-search d-flex align-items-center">
    <%= link_to root_path, class: "navbar-brand" do %>
      <div id="growlogo">
        <h1 class="logotextdark">let it gr<img class="plantlogo" src="<%= asset_path('plantblack.png') %>" alt="">w</h1></i>
      </div>
      <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

  </div>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dark dark-hover">
          <%= link_to "List my garden", "#newgardenmodal", class: "nav-link", "data-toggle": "modal" %>
        </li>
        <li class="nav-item dark-hover">
          <%= link_to "Find a garden", gardens_path, class: "nav-link" %>
        </li>
        <li class="nav-item dark-hover">
          <%= link_to "My bookings", bookings_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.url.nil? %>
            <%= image_tag('avatar-default-picture.jpg', class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false )%>
          <% else  %>
            <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item d-flex">
          <%= render 'devise/sessions/new'%>
          <%= render 'devise/registrations/new'%>
          <%= link_to "Gardens", gardens_path, class: "nav-link nav-font-black" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<div id="newgardenmodal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <p>List your garden</p>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body row">
      <p class="modaltext col-10">Make the most of your outside space whilst helping others to live more sustainably. </p>
      <%= link_to new_garden_path do  %>
      <p class="modalplant col-2"><i class="fab fa-pagelines"></i></p>
      <% end %>
      </div>
      <div class="modal-footer">
        <%= link_to "Find out more", new_garden_path, id: "modallink" %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="show-container">
  <div class="cards-container">
    <div class="card-container-user">
      <div class="item-card">
        <% if current_user.photo.url.nil? %>
          <%= image_tag('avatar-default-picture.jpg') %>
        <% else  %>
          <%= cl_image_tag current_user.photo %>
        <% end %>
        <div class="card-product-infos">
          <div class="user-infos">
            <h4>Username: <%= current_user.username %></h4>
            <h4>Bio: <%= current_user.bio %></h4>
          </div>
          <div class="first-button">
            <div><span class="btn-update"><%= link_to "Update profile", edit_user_path %></span></div>
            <div><span class="btn-update"><%= link_to "My bookings", bookings_path %></span></div>
          </div>
        </div>
      </div>
    </div>
      <h3 style="margin: 40px 0px 20px">My Garden</h3>
    <div>
      <div class="row">
        <%  current_user.gardens.each do |garden| %>
          <div class="item-card p-10">
          <% if garden.photo.url.nil? %>
            <%= image_tag('avatar-default-picture.jpg') %>
            <% else  %>
              <%= cl_image_tag garden.photo %>
            <% end %>
              <h4>Name: <%= garden.name %></h4>
              <h4>Location: <%= garden.location %></h4>
              <h4>Purpose: <%= garden.purpose %></h4>
              <h4>Price: <%= garden.price_per_day %></h4>
              <h4>Size: <%= garden.size %></h4>
              <div style="text-align: center; flex-grow: 1;"><button type="button" class="btn btn-success" data-toggle="modal" data-target="#exampleModalCenter">
                Update my garden
              </button>
              </div>
            <%= render 'shared/update-garden', garden: garden %>
        </div>
        <% end %>
      </div>

      </div>
      <br>

    </div>
  </div>
</div>